version: '2'
services:
    base:
        build:
            context: .
            dockerfile: base/Dockerfile
        image:  itamtao/base:cuda9
    base.db:
        build:
            context: .
            dockerfile: base-with-db/Dockerfile
        image:  itamtao/base-db:cuda9
        depends_on:
          - base
    pytorch-mpi:
        build:
            context: .
            dockerfile: pytorch-mpi/Dockerfile
        image:  itamtao/pytorch-mpi:cuda9
        depends_on:
          - base.db

