version: '2.3'

services:
  worker:
    container_name: lin-worker
    image: itamtao/pytorch-mpi:cuda9
    volumes:
        #      - /mlo-container-scratch/tlin/:/mlodata1/tlin
      - /home/lin/mount_from_mlodata1/:/mlodata1/tlin
    command: ["sleep", "infinity"]
    environment:
      JOBMONITOR_TIMESERIES_HOST: localhost
    runtime: nvidia
    networks:
      - net
  timeseries:
    container_name: lin-timeseries
    image: influxdb:1.7
    volumes:
      - /mlo-container-scratch/tlin/databases/runtime-influxdb:/var/lib/influxdb
      # - /Users/lin/Desktop/test:/var/lib/influxdb
    networks:
      - net

networks:
  net:
