apiVersion: v1
kind: Pod
metadata:
  name: lin-metadata
  labels:
    name: lin-metadata
    user: lin
spec:
  containers:
    - name: mongo
      image: mongo:4.0
      ports:
      - containerPort: 27017
        name: http
      volumeMounts:
      - mountPath: /data/db
        name: mlodata
        subPath: tlin/databases/metadata-mongodb
  volumes:
  - name: mlodata
    persistentVolumeClaim:
      claimName: mlo-scratch

---

apiVersion: v1
kind: Service
metadata:
  name: lin-timeseries
  labels:
    user: lin
spec:
  type: NodePort
  ports:
  - name: http
    port: 27017
    protocol: TCP
  selector:
    name: lin-metadata
