apiVersion: v1
kind: Pod
metadata:
  name: lin-worker
  labels:
    name: lin-worker
    role: worker
    user: lin
spec:
  containers:
    - name: lin-worker
      image: ic-registry.epfl.ch/mlo/pytorch-mpi:test
      imagePullPolicy: Always
      env:
        - name: JOBMONITOR_TIMESERIES_HOST
          value: lin-timeseries
        - name: JOBMONITOR_METADATA_HOST
          value: lin-metadata
      resources:
        limits:
          nvidia.com/gpu: 0
      command:
       - "/bin/bash"
       - "-c"
       - "--"
      args :
       - '/entrypoint.sh; sleep infinity'
      volumeMounts:
        - mountPath: /mlodata1
          name: mlodata
  volumes:
    - name: mlodata
      persistentVolumeClaim:
        claimName: mlo-scratch
