apiVersion: v1
kind: Pod
metadata:
  name: lin-timeseries
  labels:
    name: lin-timeseries
    user: lin
spec:
  containers:
    - name: influxdb
      image: influxdb:1.7
      ports:
      - containerPort: 8086
        name: api
      volumeMounts:
      - mountPath: /var/lib/influxdb
        name: mlodata
        subPath: tlin/databases/runtime-influxdb
  volumes:
  - name: mlodata
    persistentVolumeClaim:
      claimName: mlo-scratch

---

apiVersion: v1
kind: Service
metadata:
  name: lin-timeseries
  labels:
    user: lin
spec:
  type: NodePort
  ports:
  - name: http
    port: 8086
    protocol: TCP
  selector:
    name: lin-timeseries
