apiVersion: v1
kind: Pod
metadata:
  name: data
  labels:
    name: data
    role: master
spec:
  containers:
    - name:  data
      image: itamtao/pytorch-mpi:cuda9
      command:
        - sleep
        - infinity
      ports:
        - containerPort: 8888
          name: notebook
        - containerPort: 6006
          name: tensorboard
        - containerPort: 22
          name: ssh
      env:
        - name: ROLE
          value: "master"
      volumeMounts:
        - mountPath: /mlodata1
          name: my-pvc-nfs
  volumes:
    - name: my-pvc-nfs
      persistentVolumeClaim:
        claimName: nfs
---
apiVersion: v1
kind: Service
metadata:
  name: net
  labels:
    name: net
spec:
  type: LoadBalancer
  ports:
    - port: 8888
      name: notebook
    - port: 6006
      name: tensorboard
    - port: 22
      name: ssh
  selector:
    name: net
