apiVersion: v1
kind: ReplicationController
metadata:
  name: dmlb-worker
  labels:
    name: dmlb-worker
spec:
  replicas: 14
  selector:
    name: dmlb-worker
  template:
    metadata:
      labels:
        name: dmlb-worker
    spec:
      nodeSelector:
        cloud.google.com/gke-preemptible: "true"
      containers:
        - name: dmlb-worker
          image: itamtao/pytorch-mpi:cuda9
          imagePullPolicy: Always
          stdin: true
          tty: true
          command:
            - sleep
            - infinity
          ports:
            - containerPort: 8888
              name: notebook
            - containerPort: 6006
              name: tensorboard
            - containerPort: 22
              name: ssh
          env:
            - name: ROLE
              value: "worker"
          resources:
            limits:
              nvidia.com/gpu: 2
          volumeMounts:
            - mountPath: /mlodata1
              name: my-pvc-nfs
            - mountPath: /dev/shm
              name: dshm
      volumes:
        - name: my-pvc-nfs
          persistentVolumeClaim:
            claimName: nfs
        - name: dshm
          emptyDir:
            medium: Memory
